### Riot KEY

key="RIOT API"

### Discord KEY

TOKEN = "DISCORD BOT TOKEN"

### Database

userDB='USER'
passDB='PASSWORD'
dbName='DATABASE NAME'
PORT=3306 #Default might be 3306
HOST='IP/LOCALHOST/WHERE IS THE HOST OF THE DB'
